version: '3.8'

networks:
  WEB:

services:
  MariaDB:
    image: mariadb:latest
    container_name: db_server
    volumes:
      - /opt/mysql_wp:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db_wp
      - MYSQL_USER=user_wp
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    networks:
      - WEB
